using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class TMXMap
{
    public int TrackID;
    public int UserID;
    public string Username;
    public string UploadedAt;
    public string UpdatedAt;
    public string Name;
    public string TypeName;
    public string MapType;
    public string TitlePack;
    public bool Hide;
    public string StyleName;
    public string Mood;
    public int DisplayCost;
    public string ModName;
    public int Lightmap;
    public string ExeVersion;
    public string ExeBuild;
    public string EnvironmentName;
    public string VehicleName;
    public bool UnlimiterRequired;
    public string RouteName;
    public string LengthName;
    public int Laps;
    public string DifficultyName;
    public string ReplayTypeName;
    public int ReplayWRID;
    public int ReplayCount;
    public int TrackValue;
    public string Comments;
    public bool Unlisted;
    public int AwardCount;
    public int CommentCount;
    public int MappackID;
    public int ReplayWRTime;
    public int ReplayWRUserID;
    public string ReplayWRUsername;
    public bool Unreleased;
    public bool Downloadable;
    public string GbxMapName;
    public int RatingVoteCount;
    public int RatingVoteAverage;
    public string TrackUID;
    public bool HasScreenshot;
    public bool HasThumbnail;
    public bool HasGhostBlocks;
    public int EmbeddedObjectsCount;
    public string AuthorLogin;
    public bool IsMP4;
    public bool SizeWarning;
    public bool InPLList;
    public int Status;
    public int Position;
    public string Added;
    public int AddedBy;
    public string AddedByName;
    public string FeatureComment;
    public bool FeaturePinned;
    public int ParserVersion;
    public int EmbeddedItemsSize;
    public string Tags;
    public int ImageCount;
    public string ReleaseDate;
    public string ReleaseDateString;
}
